version: '3.9'

services:
  react-native:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8081:8081"
    networks:
      - nikoroku_network

networks:
  nikoroku_network:
    external: true
